
spring:
  application:
    name: book-mgmt-basic-imperative-react
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:h2:mem:bookDb

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        "[show_sql]": true
        "[use_sql_comments]": true
        "[format_sql]": true
    open-in-view: false

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type: trace
